### ISSUE TITLE
Image_size only accepts numerical size

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/features#46]
It seems like the `image_size` parameter should behave like WP's and accept a slug (such as "thumbnail", "medium", etc) OR an array. Right now your number is automatically made a square image `$image_size = apply_filters( 'woothemes_features_image_size', array($args['size'], $args['size']), $post );
`
I believe this can be resolved like so in `woothemes-features-templates.php`:

```
$image_size = is_numeric( $args['size'] ) ? array( $args['size'], $args['size'] ) : $args['size'];
$image_size = apply_filters( 'woothemes_features_image_size', $image_size, $post );
```

**Comment by helgatheviking** [comment]
This is 50% solved as I see the above is now in the current code. But the widget size parameter is converted automatically to an integer with `intval()`

**Comment by jeffikus** [comment]
@helgatheviking can you pop me your wp.org profile name so I can add you to the list of contributors :+1:  thanks!
