### ISSUE TITLE
Front end styles

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/features#47]
If the number of features per row is an option, it seems like there ought to be a minimal amount of front-end CSS to actually achieve that.

**Comment by jeffikus** [comment]
@danieldudzic keen to tackle this?

**Comment by danieldudzic** [comment]
@jeffikus For sure. I'll have a look at this, later today.

**Comment by jeffikus** [comment]
Brilliant, you tackle yet? @danieldudzic

**Comment by danieldudzic** [comment]
@jeffikus Didn't have time on Firday for this. Will have a look today.

**Comment by danieldudzic** [comment]
@jeffikus Right, so this is consistent across all our free plugins: https://github.com/woothemes/testimonials, https://github.com/woothemes/features and https://github.com/woothemes/our-team/
None of those load any front-end styles.

This seems to be deliberate, so if we decide to start including front-end styles, we might as well, just go, and do that for all plugins.

Currently, we simply "add support" ( include basic styling ) in our themes for all of the mentioned plugins : http://cld.wthms.co/up3z/ehCOClWu

Perhaps, @mattyza could share his thoughts on this?

**Comment by mattyza** [comment]
@danieldudzic @jeffikus @helgatheviking The intention with these plugins was to explicitly include no frontend styling.

That being said, in the cases of layout-related CSS, it makes sense.

I'd disable this by default, however, and have themes load in the styles either via an enqueue or `add_theme_support( 'woothemes_features_styles' )` of some sort.

That would prevent issues with existing implementations, while also enabling easier access to these styles for new themes.

Thoughts?

**Comment by helgatheviking** [comment]
As usual, @mattyza chimes in with some good advice! :+1:  for `add_theme_support()`. or even a plugin option if either plugin already has options. 

>The intention with these plugins was to explicitly include no frontend styling.

And I agree with that. I did the same with Simple User Listing, which is pretty much an Our Team for existing users. I built the thing because I was so annoyed with the existing solutions that all imposed too much style.

*But* when the shortcode has an option for number of members per row and then nothing happens on the front-end, that's kind of annoying! 

If it *only* did some fluid columns and you named it something even more generic like `woothemes_columns_styles` you could probably reuse it across your plugins and once enqueued you wouldn't need to use it twice. 

Here's a quick stab:

```
.features .feature { float: left; margin-right: 4%; }
.columns-2 .feature { width:48%; }
.columns-3 .feature { width:30.66%; }
.columns-4 .feature { width:22%; }
.columns-5 .feature { width:16.8%; }
.columns-6 .feature { width:13.33%; }
.features .first { clear: both; }
.features .last { margin-right: 0; }
```

Though I have always struggled with the first/last classes when trying to make the columns responsive, ie: 2up on tablet and 4up on desktops.

**Comment by mattyza** [comment]
I like the idea of an enqueued style sheet, which can be turned on
programmatically, rather than a setting or using add_theme_support(). The
enqueue feels like the cleanest solution, to me.

On Monday, August 24, 2015, Kathy <notifications@github.com> wrote:

> As usual, @mattyza <https://github.com/mattyza> chimes in with some good
> advice! [image: :+1:] for add_theme_support(). or even a plugin option if
> either plugin already has options.
>
> The intention with these plugins was to explicitly include no frontend
> styling.
>
> And I agree with that. I did the same with Simple User Listing, which is
> pretty much an Our Team for existing users. I built the thing because I was
> so annoyed with the existing solutions that all imposed too much style.
>
> *But* when the shortcode has an option for number of members per row and
> then nothing happens on the front-end, that's kind of annoying!
>
> If it *only* did some fluid columns and you named it something even more
> generic like woothemes_columns_styles you could probably reuse it across
> your plugins and once enqueued you wouldn't need to use it twice.
>
> Here's a quick stab:
>
> .features .feature { float: left; margin-right: 4%; }
> .columns-2 .feature { width:48%; }
> .columns-3 .feature { width:30.66%; }
> .columns-4 .feature { width:22%; }
> .columns-5 .feature { width:16.8%; }
> .columns-6 .feature { width:13.33%; }
> .features .first { clear: both; }
> .features .last { margin-right: 0; }
>
> Though I have always struggled with the first/last classes when trying to
> make the columns responsive, ie: 2up on tablet and 4up on desktops.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/features/issues/47#issuecomment-134278016>.
>


-- 
Matt Cohen
Woo Chief Product Officer | Automattic

http://automattic.com/
http://woothemes.com/
http://matty.co.za/

Ask me questions via Clarity: https://clarity.fm/mattcohen/

**Comment by jeffikus** [comment]
I'm happy with enqueued style sheet @mattyza - @danieldudzic you still happy to do PR?

**Comment by danieldudzic** [comment]
@jeffikus Sure, yeah, this sounds like a good solution.

I'll try to have something ready by the end of this week :)

**Comment by mattyza** [comment]
@jeffikus @danieldudzic - To clarify, I'm referring actually to `wp_register_style', not an enqueue. Poor wording on my part. :)

**Comment by tiagonoronha** [comment]
@danieldudzic ping me when you are done and I'll review. :)

**Comment by danieldudzic** [comment]
Hey @tiagonoronha ( cc: @jeffikus ),

Ok, I have added some basic frontend styles.

They are pretty much the same as in Canvas ( Features Integration ).

The `layout.css` file will get enqueued in case the current theme doesn't declare support for `features-by-woothemes` or the `woothemes_features_layout_css` filter is set to `true`.

Please let me know, if you see any room for improvement :)
