### ISSUE TITLE
Excerpt strips out HTML

### ISSUE THREAD

**Issue by TinyGiantStudios** [woothemes/features#49]
Link to ticket: https://woothemes.zendesk.com/agent/tickets/282236

When adding HTML (in this case a ```<a>``` en ```<br />```tag), it gets stripped out on the front end. Confirmed on local testing environment.

Setup in backend: http://cld.wthms.co/14OxB
Display on frontend: http://cld.wthms.co/14OxB

**Comment by jeffikus** [comment]
Ok, I can see what the code is doing - I'll follow up with @jameskoster today to understand why it was built this way.

**Comment by jeffikus** [comment]
The excerpt filters out html by default apparently - a lengthy discourse if you wanna understand why -> http://wordpress.stackexchange.com/questions/141125/allow-html-in-excerpt
